version: '3'
services:
  db:
    image: mysql:5.7
    container_name: unipro-db-wordpress
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mormbathie98
      MYSQL_DATABASE: unipro
      MYSQL_USER: mormbathie98
      MYSQL_PASSWORD: mormbathie98
    
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: unipro-wordpress
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3307
      WORDPRESS_DB_USER: mormbathie98
      WORDPRESS_DB_PASSWORD: mormbathie98
      WORDPRESS_DB_NAME: unipro

volumes:
  db_data: {}